env:                                                                                                             
  browser: true                                                                                                  
  commonjs: true                                                                                                 
  es6: true                                                                                                      
  mocha: true                                                                                                    
extends:                                                                                                         
  - 'eslint:recommended'                                                                                         
  - 'plugin:@typescript-eslint/eslint-recommended'                                                               
  - 'plugin:@typescript-eslint/recommended'                                                                      
globals:                                                                                                         
  Atomics: readonly                                                                                              
  SharedArrayBuffer: readonly                                                                                    
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 11
plugins:
  - '@typescript-eslint'
rules: {
  no-use-before-define: 'off',
  '@typescript-eslint/no-use-before-define': 'off',
  '@typescript-eslint/no-explicit-any': 'off',
  '@typescript-eslint/camelcase': 'off',
  '@typescript-eslint/no-var-requires': 'off'
}